language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
#  - osx

sudo: false
cache: pip
install: "pip install -r requirements.txt"
install: "pip install ."
script: echo "done" #(cd ./docs_gen && make html)